version: "3.8"

services:
  api:
    container_name: api
    restart: unless-stopped
    image: keepr-api
    build:
      context: theFinale
      target: production
      dockerfile: Dockerfile
    ports:
      - 7045:7045
    networks:
      - shared-network

  client:
    container_name: client
    restart: unless-stopped
    image: keepr-client
    build:
      context: theFinale.client
      target: production
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
